spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_db?currentSchema=industry
    username: dev_db
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: industry
    drop-first: true
server:
  servlet:
    context-path: /api