apiVersion: apps/v1
kind: Deployment
metadata:
  name: industry-app-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: industry-app-api
  template:
    metadata:
      labels:
        app: industry-app-api
    spec:
      containers:
        - name: industry-app-api
          image: main-docker-registry/industry-app-api:tag
          command: ["java","-jar","/app-0.0.1-SNAPSHOT.jar", "--spring.profiles.active=pro"]