apiVersion: v1
kind: Service
metadata:
  name: industry-app-api-service
spec:
  selector:
    app: industry-app-api
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer
